/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-background": "var(--color-on-background)",
                "on-secondary": "var(--color-on-secondary)",
                "inverse-on-surface": "var(--color-inverse-on-surface)",
                "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
                "on-primary": "var(--color-on-primary)",
                "on-surface": "var(--color-on-surface)",
                "surface-bright": "var(--color-surface-bright)",
                "on-secondary-container": "var(--color-on-secondary-container)",
                "surface-container-high": "var(--color-surface-container-high)",
                "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
                "surface-tint": "var(--color-surface-tint)",
                "on-primary-container": "var(--color-on-primary-container)",
                "inverse-surface": "var(--color-inverse-surface)",
                "outline": "var(--color-outline)",
                "secondary-fixed": "var(--color-secondary-fixed)",
                "error": "var(--color-error)",
                "tertiary-fixed": "var(--color-tertiary-fixed)",
                "primary-fixed": "var(--color-primary-fixed)",
                "surface-container-low": "var(--color-surface-container-low)",
                "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
                "on-tertiary-container": "var(--color-on-tertiary-container)",
                "on-surface-variant": "var(--color-on-surface-variant)",
                "error-container": "var(--color-error-container)",
                "inverse-primary": "var(--color-inverse-primary)",
                "tertiary": "var(--color-tertiary)",
                "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
                "surface-variant": "var(--color-surface-variant)",
                "on-tertiary": "var(--color-on-tertiary)",
                "on-error": "var(--color-on-error)",
                "on-error-container": "var(--color-on-error-container)",
                "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
                "secondary": "var(--color-secondary)",
                "surface-container": "var(--color-surface-container)",
                "on-primary-fixed": "var(--color-on-primary-fixed)",
                "primary-container": "var(--color-primary-container)",
                "background": "var(--color-background)",
                "surface": "var(--color-surface)",
                "on-secondary-fixed": "var(--color-on-secondary-fixed)",
                "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
                "surface-dim": "var(--color-surface-dim)",
                "tertiary-container": "var(--color-tertiary-container)",
                "primary-fixed-dim": "var(--color-primary-fixed-dim)",
                "outline-variant": "var(--color-outline-variant)",
                "surface-container-lowest": "var(--color-surface-container-lowest)",
                "secondary-container": "var(--color-secondary-container)",
                "primary": "var(--color-primary)",
                "surface-container-highest": "var(--color-surface-container-highest)"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            spacing: {
                "sm": "8px",
                "xl": "40px",
                "container-max": "1280px",
                "xs": "4px",
                "md": "16px",
                "base": "4px",
                "lg": "24px",
                "gutter": "24px"
            },
            fontFamily: {
                "headline-lg": ["Inter"],
                "headline-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "headline-sm": ["Inter"],
                "display": ["Inter"],
                "body-lg": ["Inter"],
                "label-md": ["Inter"],
                "body-md": ["Inter"],
                "label-sm": ["Inter"],
                "body-sm": ["Inter"]
            },
            fontSize: {
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
                "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
            }
        },
    },
    plugins: [],
}
